package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CurrType generated by hbm2java
 */
public class CurrType  implements java.io.Serializable {


     private Integer idcurrType;
     private String type;
     private Set projects = new HashSet(0);

    public CurrType() {
    }

    public CurrType(String type, Set projects) {
       this.type = type;
       this.projects = projects;
    }
   
    public Integer getIdcurrType() {
        return this.idcurrType;
    }
    
    public void setIdcurrType(Integer idcurrType) {
        this.idcurrType = idcurrType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }




}


