package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * IncomeType generated by hbm2java
 */
public class IncomeType  implements java.io.Serializable {


     private Integer idincomeType;
     private String type;
     private Set invoices = new HashSet(0);

    public IncomeType() {
    }

    public IncomeType(String type, Set invoices) {
       this.type = type;
       this.invoices = invoices;
    }
   
    public Integer getIdincomeType() {
        return this.idincomeType;
    }
    
    public void setIdincomeType(Integer idincomeType) {
        this.idincomeType = idincomeType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


