package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private IncomeType incomeType;
     private InvoiceType invoiceType;
     private Project project;
     private Date date;
     private Double amount;
     private Double vatAmount;
     private Double nbtAmount;
     private String total;
     private Set recipts = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(IncomeType incomeType, InvoiceType invoiceType, Project project) {
        this.incomeType = incomeType;
        this.invoiceType = invoiceType;
        this.project = project;
    }
    public Invoice(IncomeType incomeType, InvoiceType invoiceType, Project project, Date date, Double amount, Double vatAmount, Double nbtAmount, String total, Set recipts) {
       this.incomeType = incomeType;
       this.invoiceType = invoiceType;
       this.project = project;
       this.date = date;
       this.amount = amount;
       this.vatAmount = vatAmount;
       this.nbtAmount = nbtAmount;
       this.total = total;
       this.recipts = recipts;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public IncomeType getIncomeType() {
        return this.incomeType;
    }
    
    public void setIncomeType(IncomeType incomeType) {
        this.incomeType = incomeType;
    }
    public InvoiceType getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(InvoiceType invoiceType) {
        this.invoiceType = invoiceType;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Double getVatAmount() {
        return this.vatAmount;
    }
    
    public void setVatAmount(Double vatAmount) {
        this.vatAmount = vatAmount;
    }
    public Double getNbtAmount() {
        return this.nbtAmount;
    }
    
    public void setNbtAmount(Double nbtAmount) {
        this.nbtAmount = nbtAmount;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getRecipts() {
        return this.recipts;
    }
    
    public void setRecipts(Set recipts) {
        this.recipts = recipts;
    }




}


