package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceType generated by hbm2java
 */
public class InvoiceType  implements java.io.Serializable {


     private Integer idinvoiceType;
     private String type;
     private Set invoices = new HashSet(0);

    public InvoiceType() {
    }

    public InvoiceType(String type, Set invoices) {
       this.type = type;
       this.invoices = invoices;
    }
   
    public Integer getIdinvoiceType() {
        return this.idinvoiceType;
    }
    
    public void setIdinvoiceType(Integer idinvoiceType) {
        this.idinvoiceType = idinvoiceType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


