package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private Integer idproject;
     private Client client;
     private CurrType currType;
     private String name;
     private Date startDate;
     private Date endDate;
     private Double totContValue;
     private Set invoices = new HashSet(0);

    public Project() {
    }

	
    public Project(Client client, CurrType currType) {
        this.client = client;
        this.currType = currType;
    }
    public Project(Client client, CurrType currType, String name, Date startDate, Date endDate, Double totContValue, Set invoices) {
       this.client = client;
       this.currType = currType;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.totContValue = totContValue;
       this.invoices = invoices;
    }
   
    public Integer getIdproject() {
        return this.idproject;
    }
    
    public void setIdproject(Integer idproject) {
        this.idproject = idproject;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public CurrType getCurrType() {
        return this.currType;
    }
    
    public void setCurrType(CurrType currType) {
        this.currType = currType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Double getTotContValue() {
        return this.totContValue;
    }
    
    public void setTotContValue(Double totContValue) {
        this.totContValue = totContValue;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


