package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recipt generated by hbm2java
 */
public class Recipt  implements java.io.Serializable {


     private Integer idrecipt;
     private Invoice invoice;
     private User user;
     private Date date;
     private Double amount;

    public Recipt() {
    }

	
    public Recipt(Invoice invoice, User user) {
        this.invoice = invoice;
        this.user = user;
    }
    public Recipt(Invoice invoice, User user, Date date, Double amount) {
       this.invoice = invoice;
       this.user = user;
       this.date = date;
       this.amount = amount;
    }
   
    public Integer getIdrecipt() {
        return this.idrecipt;
    }
    
    public void setIdrecipt(Integer idrecipt) {
        this.idrecipt = idrecipt;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


