package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1



/**
 * TaxAmount generated by hbm2java
 */
public class TaxAmount  implements java.io.Serializable {


     private Integer idtaxAmount;
     private String type;
     private Double amount;

    public TaxAmount() {
    }

    public TaxAmount(String type, Double amount) {
       this.type = type;
       this.amount = amount;
    }
   
    public Integer getIdtaxAmount() {
        return this.idtaxAmount;
    }
    
    public void setIdtaxAmount(Integer idtaxAmount) {
        this.idtaxAmount = idtaxAmount;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


