package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaxType generated by hbm2java
 */
public class TaxType  implements java.io.Serializable {


     private Integer idtaxType;
     private String type;
     private Set clients = new HashSet(0);

    public TaxType() {
    }

    public TaxType(String type, Set clients) {
       this.type = type;
       this.clients = clients;
    }
   
    public Integer getIdtaxType() {
        return this.idtaxType;
    }
    
    public void setIdtaxType(Integer idtaxType) {
        this.idtaxType = idtaxType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


