package modal;
// Generated Jul 31, 2018 12:10:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String usename;
     private String password;
     private Set recipts = new HashSet(0);

    public User() {
    }

    public User(String usename, String password, Set recipts) {
       this.usename = usename;
       this.password = password;
       this.recipts = recipts;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getUsename() {
        return this.usename;
    }
    
    public void setUsename(String usename) {
        this.usename = usename;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getRecipts() {
        return this.recipts;
    }
    
    public void setRecipts(Set recipts) {
        this.recipts = recipts;
    }




}


